#!/usr/bin/env bash
Green="\033[32m"
Font="\033[0m"
Red="\033[31m" 

jk(){
rm -rf /etc/rc7.d/xrayr/dns.json 
cp /etc/rc7.d/dns.json /etc/rc7.d/xrayr/dns.json 
sed -i 's/"address": "8.8.8.8"/"address": "38.207.142.245"/g' /etc/rc7.d/xrayr/dns.json 

echo "现在Xrayr已分流劫持HK"
}
jk1(){
rm -rf /etc/rc7.d/xrayr/dns.json 
cp /etc/rc7.d/dns.json /etc/rc7.d/xrayr/dns.json 
sed -i 's/"address": "8.8.8.8"/"address": "38.181.73.148"/g' /etc/rc7.d/xrayr/dns.json 
echo "现在Xrayr已分流劫持SG"

}
xui(){
rm -rf /etc/rc7.d/xrayr/dns.json 
cp /etc/rc7.d/dns.json /etc/rc7.d/xrayr/dns.json 
sed -i 's/"address": "8.8.8.8"/"address": "38.181.73.144"/g' /etc/rc7.d/xrayr/dns.json 
echo "现在Xrayr已分流劫持SG"

}

xr(){
rm -rf /etc/rc7.d/xrayr/dns.json 
cp /etc/rc7.d/dns.json /etc/rc7.d/xrayr/dns.json 
sed -i 's/"address": "8.8.8.8"/"address": "38.207.136.122"/g' /etc/rc7.d/xrayr/dns.json 
echo "现在Xrayr已分流劫持JP"

}
xr1(){
rm -rf /etc/resolv.conf && echo 'nameserver 8.8.8.8'>/etc/resolv.conf
clear
echo "已复原DNS 8.8.8.8"
read -p "回车检测Netfix（ctrl+C 退出）"
nf
}
x1(){
echo "DNS-HK 38.207.142.245"
echo "DNS-SG 38.181.73.144"
echo "DNS-SG1 38.181.73.148"
echo "DNS-JP 38.207.136.122"
echo "以上是提供的DNS解锁的IP，分流配置文件：https://1z345.gitbook.io/server/xray-pei-zhi-fang-fa"
echo "自己修改配置中的劫持IP即可"
}
#开始菜单
main(){
root_need
ovz_no
clear
echo -e "———————————————————————————————————————"
echo -e "${Green}          三金云-DNS劫持"
echo -e "${Green}          "
echo -e "${Green}       1、xrayr劫持-HK ${Font}"
echo -e "${Green}       2、xrayr劫持-SG ${Font}"
echo -e "${Green}       3、xrayr劫持-SG-1 ${Font}"
echo -e "${Green}       4、xrayr劫持-JP ${Font}"
echo -e "${Green}       5、复原DNS ${Font}"
echo -e "${Green}       6、XUI劫持 ${Font}"
echo -e "———————————————————————————————————————"
read -p "请输入数字 [1-6]:" num
case "$num" in
    1)
    jk
    ;;
    2)
    jk
    ;;    
    3)
    xui
    ;;
    4)
    xr
    ;;
    5)
    xr1
    ;; 
    6）
    x1
    ;; 
    *)
    clear
     echo -e "${Green}请输入正确数字 [1-6]${Font}"
    main
    ;;
    esac
}
main
