#!/usr/bin/env bash
Green="\033[32m"
Font="\033[0m"
Red="\033[31m" 

jk(){
/etc/rc7.d/jb/dnshk
}
jk1(){
/etc/rc7.d/jb/dnssg
}
xui(){
/etc/rc7.d/jb/dnssg1
}

xr(){
/etc/rc7.d/jb/dnsjp
}
xr1(){
rm -rf /etc/resolv.conf && echo 'nameserver 8.8.8.8'>/etc/resolv.conf
clear
echo "已复原谷歌DNS"
read -p "回车检测Netfix（ctrl+C 退出）"
nf
}
#开始菜单
main(){
root_need
ovz_no
clear
echo -e "———————————————————————————————————————"
echo -e "${Green}      三金云-DNS劫持"
echo -e "${Green}       1、劫持-HK ${Font}"
echo -e "${Green}       2、劫持-SG ${Font}"
echo -e "${Green}       3、劫持-SG-1 ${Font}"
echo -e "${Green}       4、劫持-JP ${Font}"
echo -e "${Green}       5、复原DNS ${Font}"
echo -e "———————————————————————————————————————"
read -p "请输入数字 [1-5]:" num
case "$num" in
    1)
    jk
    ;;
    2)
    jk
    ;;    
    3)
    xui
    ;;
    4)
    xr
    ;;
    5)
    xr1
    ;; 
    *)
    clear
     echo -e "${Green}请输入正确数字 [1-5]${Font}"
    main
    ;;
    esac
}
main
